version: "3"

services:
  db:
    image: postgres
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - env/.env.local
    ports:
      - 5432:5432

  web:
    build: .
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver localhost:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db