current_dir = $(shell pwd)

start_local:
	docker-compose -f docker-compose.yml up -d;

stop_local:
	docker-compose -f docker-compose.yml stop;

build_local:
	docker-compose -f docker-compose.yml build;

down_local:
	docker-compose -f docker-compose.yml down;
